apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azurekeyvault
  namespace: default
spec:
  type: secretstores.azure.keyvault
  metadata:
  - name: vaultName
    value: corona-keys
  - name: spnTenantId
    value: "<tenant-id>"
  - name: spnClientId
    value: "<client-id>"
  - name: spnCertificateFile
    value : "certificate.pfx"